controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController


ackermann_steering_controller:
  ros__parameters:
    publish_rate: 30.0

    base_frame_id: base_link

    rear_wheels_names: ["rear_left_wheel_joint", rear_right_wheel_joint]
    front_wheels_names: ["front_left_steer_joint", front_right_steer_joint]

    front_wheel_track: 0.125
    rear_wheel_track: 0.125
    wheelbase: 0.135
    front_wheels_radius: 0.0325
    rear_wheels_radius: 0.0325

    front_steering: true

    enable_odom_tf: true
    position_feedback: false
    use_stamped_vel: true

