<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="doteacher" params="prefix">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931" />
    <xacro:property name="base_mass" value="1.5" /> <!-- arbitrary value for base mass -->
    <xacro:property name="base_width" value="0.125" />
    <xacro:property name="base_length" value="0.29" />
    <xacro:property name="base_height" value="0.14" />
    <xacro:property name="wheelbase" value="0.135" />
    <xacro:property name="wheel_mass" value="0.05" /> <!-- arbitrary value for wheel mass -->
    <xacro:property name="wheel_len" value="0.02" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <!-- <xacro:property name="wheeltrack" value="" -->

    <xacro:property name="wheel_friction" value="0.5" />

    <!-- Base Link -->
    <link name="${prefix}base_link" />

    <!-- Base Footprint Link -->
    <link name="${prefix}base_footprint" />

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}base_footprint" />
      <origin xyz="0 0 -${wheel_radius}" rpy="0 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <!-- Chassis -->
    <link name="${prefix}chassis_link">
      <collision>
        <origin xyz="${base_length/2-0.01} 0 ${base_height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}" />
        </geometry>   
      </collision>

      <visual>
        <origin xyz="${base_length/2-0.01} 0 ${base_height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}" />
        </geometry>
        <material name="orange" />
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${base_mass}" />
        <inertia
          ixx="0.021367" ixy="0.0" ixz="0.0"
          iyy="0.016621" iyz="0.0"
          izz="0.009954" />
      </inertial>
    </link>

    <joint name="${prefix}chassis_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}chassis_link" />
      <origin xyz="-0.090 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.2" />
    </joint>

    <!-- rear wheels -->
    <!-- virtual rear wheel -->

    <link name="${prefix}virtual_rear_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="0.01" radius="${wheel_radius}" />
        </geometry>
        <material name="invisible" />
      </visual>
    </link>

    <joint name="${prefix}virtual_rear_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}virtual_rear_wheel" />
      <origin xyz="-${wheelbase/2} 0 0" rpy="0 0 ${PI/2}" />
      <axis xyz="1 0 0" />
      <limit effort="100.0" velocity="100.0" />
      <dynamics damping="0.2" />
    </joint>

    <!-- rear right wheel -->
    <link name="${prefix}rear_right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
        <material name="black" />
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <mass value="${wheel_mass}" />
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426" />
      </inertial>
    </link>


    <joint name="${prefix}rear_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}rear_right_wheel" />
      <origin xyz="-${wheelbase/2} ${base_width/2} 0" rpy="0 0 ${PI/2}" />
      <axis xyz="1 0 0" />
      <limit effort="100.0" velocity="100.0" />
      <dynamics damping="0.2" />
      <mimic joint="${prefix}virtual_rear_wheel_joint" multiplier="1.0" offset="0.0" />
    </joint>


    <!-- rear left wheel -->
    <link name="${prefix}rear_left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
        <material name="black" />
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <mass value="${wheel_mass}" />
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426" />
      </inertial>

    </link>

    <joint name="${prefix}rear_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}rear_left_wheel" />
      <origin xyz="-${wheelbase/2} -${base_width/2} 0" rpy="0 0 ${PI/2}" />
      <axis xyz="1 0 0" />
      <limit effort="100.0" velocity="100.0" />
      <dynamics damping="0.2" />
      <mimic joint="${prefix}virtual_rear_wheel_joint" multiplier="1.0" offset="0.0" />
    </joint>


    <!-- front wheels -->

    <link name="${prefix}virtual_front_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="0.01" radius="${wheel_radius}" />
        </geometry>
        <material name="invisible" />
      </visual>
    </link>

    <joint name="${prefix}virtual_front_wheel_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link="${prefix}virtual_front_wheel" />
      <origin xyz="${wheelbase/2} 0 0" rpy="0 0 ${PI/2}" />
      <axis xyz="0 0 1" />
      <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0" />
      <dynamics damping="0.2" />
    </joint>

    <!-- front right wheel -->

    <link name="${prefix}front_right_wheel">

      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
        <material name="black" />
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <mass value="${wheel_mass}" />
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426" />
      </inertial>
    </link>

    <joint name="${prefix}front_right_wheel_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link="${prefix}front_right_wheel" />
      <origin xyz="${wheelbase/2} ${base_width/2} 0" rpy="0 0 ${PI/2}" />
      <axis xyz="0 0 1" />
      <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0" />
      <dynamics damping="0.2" />
      <mimic joint="${prefix}virtual_front_wheel_joint" multiplier="1.0" offset="0.0" />
    </joint>

    <!-- front left wheel -->

    <link name="${prefix}front_left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
        <material name="black" />
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <mass value="${wheel_mass}" />
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426" />
      </inertial>

    </link>

    <joint name="${prefix}front_left_wheel_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link="${prefix}front_left_wheel" />
      <origin xyz="${wheelbase/2} -${base_width/2} 0" rpy="0 0 ${PI/2}" />
      <axis xyz="0 0 1" />
      <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0" />
      <dynamics damping="0.2" />
      <mimic joint="${prefix}virtual_front_wheel_joint" multiplier="1.0" offset="0.0" />
    </joint>


    <!-- lidar -->

    <joint name="${prefix}laser_joint" type="fixed">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}laser_frame" />
      <origin xyz="0.180 0 0.195" rpy="0 0 0" />
    </joint>

    <link name="${prefix}laser_frame">
      <visual>
        <geometry>
          <cylinder radius="0.05" length="0.04" />
        </geometry>
        <material name="red" />
      </visual>

      <collision>
        <geometry>
          <cylinder radius="0.05" length="0.04" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.05" />
        <inertia ixx="0.0001" ixy="0.000" ixz="0.000"
          iyy="0.0001" iyz="0.000" izz="0.0001" />
      </inertial>
    </link>


    <!-- camera -->

    <joint name="${prefix}camera_joint" type="fixed">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}camera_link" />
      <origin xyz="0.25 0 0.085" rpy="0 0 0" />
    </joint>

    <link name="${prefix}camera_link">
      <visual>
        <geometry>
          <box size="0.010 0.03 0.03" />
        </geometry>
        <material name="red" />
      </visual>
      <collision>
        <geometry>
          <box size="0.010 0.03 0.03" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.01" />
        <inertia ixx="0.0001" ixy="0.000" ixz="0.000"
          iyy="0.0001" iyz="0.000" izz="0.0001" />
      </inertial>
    </link>

    <joint name="${prefix}camera_optical_joint" type="fixed">
      <parent link="${prefix}camera_link" />
      <child link="${prefix}camera_link_optical" />
      <origin xyz="0 0 0" rpy="-${PI/2} 0 -${PI/2}" />
    </joint>

    <link name="${prefix}camera_link_optical">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.000001" />
        <inertia ixx="0.0001" ixy="0.000" ixz="0.000"
          iyy="0.0001" iyz="0.000" izz="0.0001" />
      </inertial>
    </link>

    <gazebo reference="base_link">
    </gazebo>

    <gazebo reference="${prefix}chassis_link">
      <damping>
        <linear>0.2</linear>
        <angular>0.05</angular>
      </damping>
      <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="${prefix}rear_right_wheel">
      <mu1>0.5</mu1>
      <mu2>0.5</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="${prefix}rear_left_wheel">
      <mu1>0.5</mu1>
      <mu2>0.5</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="${prefix}front_right_wheel">
      <mu1>0.5</mu1>
      <mu2>0.5</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="${prefix}front_left_wheel">
      <mu1>0.5</mu1>
      <mu2>0.5</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="${prefix}laser_frame">
      <sensor name="laser" type="ray">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>5</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>0.500000</resolution>
              <min_angle>0.000000</min_angle>
              <max_angle>6.280000</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.120000</min>
            <max>10</max>
            <resolution>0.015000</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
          <ros>
            <remapping>~/out:=scan</remapping>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
          <frame_name>laser_frame</frame_name>
        </plugin>
      </sensor>
      <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="${prefix}camera_link">
      <sensor name="camera" type="camera">
        <always_on>true</always_on>
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>10</update_rate>
        <camera>
          <horizontal_fov>1.089</horizontal_fov>
          <image>
            <format>R8G8B8</format>
            <width>640</width>
            <height>480</height>
          </image>
          <clip>
            <near>0.05</near>
            <far>8.0</far>
          </clip>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <frame_name>camera_link_optical</frame_name>
        </plugin>
      </sensor>
      <material>Gazebo/Red</material>
    </gazebo>

  </xacro:macro>

</robot>