/bond_disable_heartbeat_timeout: true
always_send_full_costmap: true
filters: []
footprint: '[]'
footprint_padding: 0.009999999776482582
global_frame: map
height: 5
inflation_layer.cost_scaling_factor: 10.0
inflation_layer.enabled: true
inflation_layer.inflate_around_unknown: false
inflation_layer.inflate_unknown: false
inflation_layer.inflation_radius: 0.15
inflation_layer.plugin: nav2_costmap_2d::InflationLayer
lethal_cost_threshold: 100
map_topic: /map
observation_sources: ''
obstacle_layer.combination_method: 1
obstacle_layer.enabled: true
obstacle_layer.footprint_clearing_enabled: true
obstacle_layer.max_obstacle_height: 2.0
obstacle_layer.min_obstacle_height: 0.0
obstacle_layer.observation_sources: scan
obstacle_layer.plugin: nav2_costmap_2d::ObstacleLayer
obstacle_layer.scan.clearing: true
obstacle_layer.scan.data_type: LaserScan
obstacle_layer.scan.expected_update_rate: 0.0
obstacle_layer.scan.inf_is_valid: false
obstacle_layer.scan.marking: true
obstacle_layer.scan.max_obstacle_height: 2.0
obstacle_layer.scan.min_obstacle_height: 0.0
obstacle_layer.scan.observation_persistence: 0.0
obstacle_layer.scan.obstacle_max_range: 2.5
obstacle_layer.scan.obstacle_min_range: 0.0
obstacle_layer.scan.raytrace_max_range: 3.0
obstacle_layer.scan.raytrace_min_range: 0.0
obstacle_layer.scan.sensor_frame: ''
obstacle_layer.scan.topic: /scan
origin_x: 0.0
origin_y: 0.0
plugins:
- static_layer
- obstacle_layer
- inflation_layer
publish_frequency: 1.0
resolution: 0.05
robot_base_frame: base_link
robot_radius: 0.11
rolling_window: false
static_layer.enabled: true
static_layer.footprint_clearing_enabled: true
static_layer.map_subscribe_transient_local: true
static_layer.map_topic: ''
static_layer.plugin: nav2_costmap_2d::StaticLayer
static_layer.subscribe_to_updates: false
static_layer.transform_tolerance: 0.0
track_unknown_space: true
transform_tolerance: 0.3
trinary_costmap: true
unknown_cost_value: 255
update_frequency: 1.0
use_maximum: false
use_sim_time: false
width: 5
