/bond_disable_heartbeat_timeout: true
always_send_full_costmap: true
filters: []
footprint: '[]'
footprint_padding: 0.009999999776482582
global_frame: odom
height: 3
inflation_layer.cost_scaling_factor: 10.0
inflation_layer.enabled: true
inflation_layer.inflate_around_unknown: false
inflation_layer.inflate_unknown: false
inflation_layer.inflation_radius: 0.15
inflation_layer.plugin: nav2_costmap_2d::InflationLayer
lethal_cost_threshold: 100
map_topic: /map
observation_sources: ''
origin_x: 0.0
origin_y: 0.0
plugins:
- voxel_layer
- inflation_layer
publish_frequency: 2.0
resolution: 0.05
robot_base_frame: base_link
robot_radius: 0.11
rolling_window: true
track_unknown_space: false
transform_tolerance: 0.3
trinary_costmap: true
unknown_cost_value: 255
update_frequency: 5.0
use_maximum: false
use_sim_time: false
voxel_layer.combination_method: 1
voxel_layer.enabled: true
voxel_layer.footprint_clearing_enabled: true
voxel_layer.mark_threshold: 0
voxel_layer.max_obstacle_height: 2.0
voxel_layer.min_obstacle_height: 0.0
voxel_layer.observation_sources: scan
voxel_layer.origin_z: 0.0
voxel_layer.plugin: nav2_costmap_2d::VoxelLayer
voxel_layer.publish_voxel_map: true
voxel_layer.scan.clearing: true
voxel_layer.scan.data_type: LaserScan
voxel_layer.scan.expected_update_rate: 0.0
voxel_layer.scan.inf_is_valid: false
voxel_layer.scan.marking: true
voxel_layer.scan.max_obstacle_height: 2.0
voxel_layer.scan.min_obstacle_height: 0.0
voxel_layer.scan.observation_persistence: 0.0
voxel_layer.scan.obstacle_max_range: 2.5
voxel_layer.scan.obstacle_min_range: 0.0
voxel_layer.scan.raytrace_max_range: 3.0
voxel_layer.scan.raytrace_min_range: 0.0
voxel_layer.scan.sensor_frame: ''
voxel_layer.scan.topic: /scan
voxel_layer.unknown_threshold: 15
voxel_layer.z_resolution: 0.05
voxel_layer.z_voxels: 16
width: 3
